name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, '3.0', head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bin/setup
    - name: setup git commit
      run: |
        git config --global user.email 'test@example.com'
        git config --global user.name 'Ayano Sugiura'
    - run: bundle exec rake
